<?php
declare(strict_types=1);
$packageAutoload=dirname(__DIR__).'/vendor/autoload.php';if(is_file($packageAutoload))require$packageAutoload;
$roots=['Pam\\Native\\Media\\'=>dirname(__DIR__).'/src/','Pam\\Native\\Testing\\'=>dirname(__DIR__,2).'/pam-native-testing/src/','Pam\\Native\\'=>dirname(__DIR__,2).'/../pam-native/packages/native/src/'];spl_autoload_register(static function(string $c)use($roots):void{foreach($roots as$p=>$r)if(str_starts_with($c,$p)){$f=$r.str_replace('\\','/',substr($c,strlen($p))).'.php';if(is_file($f))require$f;return;}});
use Pam\Native\Internal\Wire;use Pam\Native\Media\CameraEventKind;use Pam\Native\Media\CameraFacing;use Pam\Native\Media\CameraFlashMode;use Pam\Native\Media\CameraMode;use Pam\Native\Media\CameraView;use Pam\Native\Media\Media;use Pam\Native\Media\MediaKind;use Pam\Native\Media\ThumbnailFormat;use Pam\Native\Testing\NativeTestHarness;
$tests=[];$test=static function(string$n,Closure$f)use(&$tests):void{$tests[$n]=$f;};
$test('maps typed probe metadata',static function():void{$fake=NativeTestHarness::install();$fake->succeed('media','probe',['kind'=>3,'mimeType'=>'video/mp4','bytes'=>2048,'width'=>1920,'height'=>1080,'durationMillis'=>3200,'orientationDegrees'=>0]);$info=null;(new Media())->probe('media/a.mp4',static function($v)use(&$info):void{$info=$v;});if($info?->kind!==MediaKind::Video||$info->durationMillis!==3200)throw new RuntimeException('metadata mismatch');NativeTestHarness::uninstall();});
$test('sends thumbnail policies as integer contract',static function():void{$fake=NativeTestHarness::install();$fake->succeed('media','thumbnail',['path'=>'thumbs/a.jpg']);$path=null;(new Media())->thumbnail('media/a.mp4','thumbs/a.jpg',640,360,static function($v)use(&$path):void{$path=$v;});$payload=Wire::decodeMap($fake->lastCall()->payload);if($path!=='thumbs/a.jpg'||$payload['format']!==1||$payload['quality']!==85)throw new RuntimeException('thumbnail contract mismatch');NativeTestHarness::uninstall();});
$test('rejects absolute paths and unsafe dimensions',static function():void{try{(new Media())->thumbnail('/tmp/a','b',0,100,static function():void{});throw new RuntimeException('unsafe input accepted');}catch(InvalidArgumentException){}});
$test('builds typed camera command revisions',static function():void{$element=CameraView::make()->facing(CameraFacing::Front)->mode(CameraMode::Video)->flash(CameraFlashMode::Auto)->captureRevision(2)->recordRevision(3)->stopRevision(4)->maxDuration(30)->audio()->toElement();if(!$element instanceof Pam\Native\Element)throw new RuntimeException('camera is not renderable');});
$test('camera coded variants are sequential integers',static function():void{foreach([CameraFacing::cases(),CameraMode::cases(),CameraFlashMode::cases(),CameraEventKind::cases()]as$cases){$values=array_map(static fn($case)=>$case->value,$cases);if($values!==range(1,count($values)))throw new RuntimeException('camera enum is not sequential');}});
$test('camera captures use renderer-safe sandbox paths',static function():void{$root=dirname(__DIR__);$android=file_get_contents($root.'/android/src/main/kotlin/dev/pam/media/CameraViewFactory.kt');$ios=file_get_contents($root.'/ios/Sources/CameraViewFactory.swift');if(!is_string($android)||!str_contains($android,'pam-files/captures')||!str_contains($android,'path=capturePath(file)'))throw new RuntimeException('Android camera capture escaped the PAM file sandbox');if(!is_string($ios)||!str_contains($ios,'pam-files/captures')||!str_contains($ios,'"captures/\(url.lastPathComponent)"'))throw new RuntimeException('iOS camera capture escaped the PAM file sandbox');});

$test('serializes a transcode and long-polls progress to the result',static function():void{$fake=NativeTestHarness::install();$fake->succeed('media','transcodeStart',['task'=>4]);$fake->succeed('media','transcodeNext',['state'=>1,'progress'=>0.5]);$fake->succeed('media','transcodeNext',['state'=>2,'path'=>'outbox/a.mp4','mimeType'=>'video/mp4','width'=>720,'height'=>1280,'durationMillis'=>9000,'bytes'=>1000,'bitrate'=>888,'fastStart'=>true]);$progress=[];$result=null;$start=null;$task=Media::transcode('captures/a.mov')->to('outbox/a.mp4')->preset(Pam\Native\Media\VideoPreset::Chat720p)->maxBitrate(1_200_000)->fastStart()->progress(static function(float $p)use(&$progress):void{$progress[]=$p;})->run(static function(Pam\Native\Media\TranscodeResult $r)use(&$result):void{$result=$r;});$start=Wire::decodeMap($fake->calls()[0]->payload);$options=json_decode($start['options'],true);if($options!==['preset'=>2,'maxBitrate'=>1200000,'fastStart'=>true,'audio'=>true]||$start['source']!=='captures/a.mov')throw new RuntimeException('transcode contract mismatch');if($progress!==[0.5]||$result?->width!==720||!$result->fastStart||!$task->finished())throw new RuntimeException('transcode result mismatch');$fake->assertSatisfied();NativeTestHarness::uninstall();});
$test('reports transcode failures and requires a destination',static function():void{$fake=NativeTestHarness::install();$fake->succeed('media','transcodeStart',['task'=>1]);$fake->succeed('media','transcodeNext',['state'=>3,'message'=>'No video track']);$error=null;Media::transcode('a.mp4')->to('b.mp4')->run(static fn()=>null,static function(string $m)use(&$error):void{$error=$m;});if($error!=='No video track')throw new RuntimeException('failure not reported');NativeTestHarness::uninstall();try{Media::transcode('a.mp4')->run(static fn()=>null);throw new RuntimeException('missing destination accepted');}catch(LogicException $e){if($e instanceof RuntimeException)throw $e;}});
$test('serializes ordered image operations',static function():void{$fake=NativeTestHarness::install();$fake->succeed('media','imageProcess',['path'=>'out/a.webp','width'=>320,'height'=>240,'bytes'=>99,'mimeType'=>'image/webp']);$result=null;Media::image('in/a.jpg')->crop(10,20,640,480)->resize(320,0,Pam\Native\Media\ResizeMode::Cover)->onlyScaleDown()->rotate(-90)->flip(Pam\Native\Media\FlipDirection::Vertical)->format(Pam\Native\Media\ImageFormat::Webp,70)->save('out/a.webp',static function(Pam\Native\Media\ImageResult $r)use(&$result):void{$result=$r;});$p=Wire::decodeMap($fake->lastCall()->payload);$ops=json_decode($p['operations'],true);if($ops!==[['op'=>'crop','x'=>10,'y'=>20,'width'=>640,'height'=>480],['op'=>'resize','width'=>320,'height'=>0,'mode'=>2],['op'=>'rotate','degrees'=>270],['op'=>'flip','direction'=>2]]||$p['onlyScaleDown']!==true||$p['format']!==3||$p['quality']!==70)throw new RuntimeException('image contract mismatch');if($result?->mimeType!=='image/webp')throw new RuntimeException('image result mismatch');NativeTestHarness::uninstall();});
$test('probes images with EXIF orientation',static function():void{$fake=NativeTestHarness::install();$fake->succeed('media','imageProbe',['width'=>3000,'height'=>4000,'storedWidth'=>4000,'storedHeight'=>3000,'orientation'=>6,'mimeType'=>'image/jpeg','bytes'=>5]);$info=null;Media::image('in/a.jpg')->probe(static function($v)use(&$info):void{$info=$v;});if($info?->orientation!==Pam\Native\Media\ExifOrientation::Rotate90||$info->orientation->degrees()!==90||!$info->orientation->swapsDimensions()||$info->width!==3000)throw new RuntimeException('probe mismatch');NativeTestHarness::uninstall();});
$test('batches thumbnails preserving order and per-item errors',static function():void{$fake=NativeTestHarness::install();$fake->succeed('media','thumbnails',['results'=>json_encode([['path'=>'t/1.jpg','width'=>320,'height'=>180],['error'=>'Video frame unavailable']])]);$rows=null;Media::thumbnails([Pam\Native\Media\Thumbnail::make('v/1.mp4','t/1.jpg')->size(320,320)->at(1500),Pam\Native\Media\Thumbnail::make('https://cdn.example.test/2.mp4','t/2.jpg')->format(ThumbnailFormat::Webp,60)],static function(array $r)use(&$rows):void{$rows=$r;});$items=json_decode(Wire::decodeMap($fake->lastCall()->payload)['items'],true);if($items[0]['timeMillis']!==1500||$items[1]['format']!==3||$items[1]['source']!=='https://cdn.example.test/2.mp4')throw new RuntimeException('batch contract mismatch');if(!$rows[0]->succeeded()||$rows[1]->succeeded()||$rows[1]->error!=='Video frame unavailable'||$rows[1]->source!=='https://cdn.example.test/2.mp4')throw new RuntimeException('batch result mismatch');NativeTestHarness::uninstall();});
$test('rejects unsafe image and transcode input',static function():void{$cases=[static fn()=>Media::image('/etc/a.jpg'),static fn()=>Media::image('a/../b.jpg'),static fn()=>Media::image('a.jpg')->rotate(45),static fn()=>Media::image('a.jpg')->resize(0,0),static fn()=>Media::image('a.jpg')->format(Pam\Native\Media\ImageFormat::Jpeg,0),static fn()=>Media::transcode('a.mp4')->to('a.mp4'),static fn()=>Media::transcode('a.mp4')->maxBitrate(10),static fn()=>Pam\Native\Media\Thumbnail::make('http://x.test/a.mp4','t.jpg'),static fn()=>Media::thumbnails([],static fn()=>null)];foreach($cases as$i=>$case){try{$case();throw new RuntimeException("unsafe case $i accepted");}catch(InvalidArgumentException){}}});
$test('new coded variants are sequential and match the IDL',static function():void{$idl=json_decode((string)file_get_contents(dirname(__DIR__).'/pam-native.idl.json'),true,16,JSON_THROW_ON_ERROR);foreach($idl['enums'] as $name=>$cases){$class='Pam\\Native\\Media\\'.$name;$actual=[];foreach($class::cases() as $case)$actual[$case->name]=$case->value;if($actual!==$cases)throw new RuntimeException("$name differs from IDL");if(array_values($cases)!==range(1,count($cases)))throw new RuntimeException("$name is not sequential");}});
$test('android media resolves the PAM file sandbox and keeps the transcode entry point',static function():void{$root=dirname(__DIR__);$module=(string)file_get_contents($root.'/android/src/main/kotlin/dev/pam/media/MediaModule.kt');$rules=(string)file_get_contents($root.'/android/consumer-rules.pro');if(!str_contains($module,'File(this.context.filesDir, "pam-files")'))throw new RuntimeException('media module does not use the pam-files sandbox');if(!str_contains($rules,'dev.pam.media.MediaTranscoding'))throw new RuntimeException('transcode entry point is not kept');});
$failed=0;foreach($tests as$n=>$f){try{$f();fwrite(STDOUT,"PASS $n\n");}catch(Throwable$e){$failed++;fwrite(STDERR,"FAIL $n: {$e->getMessage()}\n");}}fwrite(STDOUT,count($tests)." tests, $failed failures\n");exit($failed?1:0);
