<?php
declare(strict_types=1);
$roots=['Pam\\Native\\Media\\'=>dirname(__DIR__).'/src/','Pam\\Native\\Testing\\'=>dirname(__DIR__,2).'/pam-native-testing/src/','Pam\\Native\\'=>dirname(__DIR__,2).'/../pam-native/packages/native/src/'];spl_autoload_register(static function(string $c)use($roots):void{foreach($roots as$p=>$r)if(str_starts_with($c,$p)){$f=$r.str_replace('\\','/',substr($c,strlen($p))).'.php';if(is_file($f))require$f;return;}});
use Pam\Native\Internal\Wire;use Pam\Native\Media\Media;use Pam\Native\Media\MediaKind;use Pam\Native\Testing\NativeTestHarness;
$tests=[];$test=static function(string$n,Closure$f)use(&$tests):void{$tests[$n]=$f;};
$test('maps typed probe metadata',static function():void{$fake=NativeTestHarness::install();$fake->succeed('media','probe',['kind'=>3,'mimeType'=>'video/mp4','bytes'=>2048,'width'=>1920,'height'=>1080,'durationMillis'=>3200,'orientationDegrees'=>0]);$info=null;(new Media())->probe('media/a.mp4',static function($v)use(&$info):void{$info=$v;});if($info?->kind!==MediaKind::Video||$info->durationMillis!==3200)throw new RuntimeException('metadata mismatch');NativeTestHarness::uninstall();});
$test('sends thumbnail policies as integer contract',static function():void{$fake=NativeTestHarness::install();$fake->succeed('media','thumbnail',['path'=>'thumbs/a.jpg']);$path=null;(new Media())->thumbnail('media/a.mp4','thumbs/a.jpg',640,360,static function($v)use(&$path):void{$path=$v;});$payload=Wire::decodeMap($fake->lastCall()->payload);if($path!=='thumbs/a.jpg'||$payload['format']!==1||$payload['quality']!==85)throw new RuntimeException('thumbnail contract mismatch');NativeTestHarness::uninstall();});
$test('rejects absolute paths and unsafe dimensions',static function():void{try{(new Media())->thumbnail('/tmp/a','b',0,100,static function():void{});throw new RuntimeException('unsafe input accepted');}catch(InvalidArgumentException){}});
$failed=0;foreach($tests as$n=>$f){try{$f();fwrite(STDOUT,"PASS $n\n");}catch(Throwable$e){$failed++;fwrite(STDERR,"FAIL $n: {$e->getMessage()}\n");}}fwrite(STDOUT,count($tests)." tests, $failed failures\n");exit($failed?1:0);
